on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    environment: develop
    steps:
     - name: test
       run: |
         echo ${{ secrets.TEST }}
         echo ${{ secrets.DOCKER_USER}}
