on:
  pull_request:
    types: [labeled]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - name: test
       run: |
         echo ${{ secrets.TEST }}
         echo ${{ secrets.DOCKER_USER}}
